[package]
name = 'day17'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.6.0"
regex = "1.10.2"

[[bin]]
name = 'day17'
path = 'main.rs'

[features]
vis = []