[package]
name = 'intcode'
version = '0.0.1'
edition = '2018'

[dependencies]
rustyline = "5.0.4"

[dependencies.cursive]
version = "0.13.0"
default-features = false
features = ["crossterm-backend"]

[[example]]
name = "debug_tui"
path = "examples/debug_tui.rs"
