[package]
name = 'day17'
version = '0.0.1'
edition = '2018'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"
kiss3d = { version = "0.35.0", optional = true }

[[bin]]
name = 'day17'
path = 'main.rs'

[features]
vis = ["dep:kiss3d"]
