[package]
name = 'day11'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"
regex = "1.10.2"
itertools = "0.12.0"

[[bin]]
name = 'day11'
path = 'main.rs'
