[package]
name = 'day12'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"
regex = "1.10.2"
rayon = "1.8.0"
lru = "0.12.1"

[[bin]]
name = 'day12'
path = 'main.rs'
