[package]
name = 'day15'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"
regex = "1.11.1"

[[bin]]
name = 'day15'
path = 'main.rs'

[features]
vis = []