[package]
name = 'day06'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"
regex = "1.11.1"
rayon = "1.8.0"

[[bin]]
name = 'day06'
path = 'main.rs'
