[package]
name = 'day16'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"
regex = "1.10.2"
rayon = "1.8.0"

[[bin]]
name = 'day16'
path = 'main.rs'

[features]
vis = []