[package]
name = 'day22'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"
kiss3d = { version = "0.35.0", optional = true }

[features]
vis = ["dep:kiss3d"]

[[bin]]
name = 'day22'
path = 'main.rs'
