[package]
name = 'day21'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.8.2"
regex = "1.10.2"
bacon-sci = "0.14.0"

[[bin]]
name = 'day21'
path = 'main.rs'
