name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  aoc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=aoc/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=aoc/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=aoc/Cargo.toml
    # - name: Check formatting of Rust code with rustfmt
    #   uses: actions-rust-lang/rustfmt@V1.1.0
    #   with:
    #     manifest-path: aoc/Cargo.toml

  year2022:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2022/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2022/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2022/Cargo.toml
    # - name: Check formatting of Rust code with rustfmt
    #   uses: actions-rust-lang/rustfmt@V1.1.0
    #   with:
    #     manifest-path: 2022/Cargo.toml

  year2021:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2021/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2021/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2021/Cargo.toml

  year2020:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2020/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2020/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2020/Cargo.toml

  year2019:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2019/Cargo.toml
    # - name: Run tests
    #   run: cargo test --verbose --manifest-path=2019/Cargo.toml
    # - name: Run clippy
    #   run: cargo clippy --manifest-path=2019/Cargo.toml

  year2017:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2017/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2017/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2017/Cargo.toml
