name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  aoc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=aoc/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=aoc/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=aoc/Cargo.toml

  formatAoc:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "date=$(date -d '1 month ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.date }}
          components: rustfmt
      - uses: LoliGothick/rustfmt-check@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly-${{ env.date }}
          flags: --all
          working-directory: aoc

  year2022:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2022/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2022/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2022/Cargo.toml

  formatYear2022:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "date=$(date -d '1 month ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.date }}
          components: rustfmt
      - uses: LoliGothick/rustfmt-check@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly-${{ env.date }}
          flags: --all
          working-directory: 2022

  year2021:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2021/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2021/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2021/Cargo.toml

  formatYear2021:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "date=$(date -d '1 month ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.date }}
          components: rustfmt
      - uses: LoliGothick/rustfmt-check@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly-${{ env.date }}
          flags: --all
          working-directory: 2021

  year2020:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2020/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2020/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2020/Cargo.toml

  formatYear2020:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "date=$(date -d '1 month ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.date }}
          components: rustfmt
      - uses: LoliGothick/rustfmt-check@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly-${{ env.date }}
          flags: --all
          working-directory: 2020

  year2019:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2019/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2019/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2019/Cargo.toml

  formatYear2019:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "date=$(date -d '1 month ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.date }}
          components: rustfmt
      - uses: LoliGothick/rustfmt-check@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly-${{ env.date }}
          flags: --all
          working-directory: 2019

  year2017:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2017/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2017/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2017/Cargo.toml

  formatYear2017:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "date=$(date -d '1 month ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.date }}
          components: rustfmt
      - uses: LoliGothick/rustfmt-check@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly-${{ env.date }}
          flags: --all
          working-directory: 2017

  year2016:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2016/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2016/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2016/Cargo.toml

  formatYear2016:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "date=$(date -d '1 month ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.date }}
          components: rustfmt
      - uses: LoliGothick/rustfmt-check@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: nightly-${{ env.date }}
          flags: --all
          working-directory: 2016
