name: Year 2022

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --manifest-path=2022/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path=2022/Cargo.toml
    - name: Run clippy
      run: cargo clippy --manifest-path=2022/Cargo.toml
    - name: Check formatting of Rust code with rustfmt
      uses: actions-rust-lang/rustfmt@V1.1.0
      inputs:
        manifest-path: 2022/Cargo.toml
